"""create initial news schema

Revision ID: d201fcfb7409
Revises: 
Create Date: 2026-06-26 18:51:48.710379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd201fcfb7409'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_users')),
    sa.UniqueConstraint('email', name=op.f('uq_app_users_email'))
    )
    op.create_table('indian_states',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('short_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region_type', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default=sa.text("'IN'"), nullable=False),
    sa.Column('capital', sa.String(length=120), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_code = 'IN'", name=op.f('ck_indian_states_country_code_india')),
    sa.CheckConstraint("region_type IN ('state', 'union_territory')", name=op.f('ck_indian_states_region_type_values')),
    sa.CheckConstraint('display_order > 0', name=op.f('ck_indian_states_display_order_positive')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_indian_states')),
    sa.UniqueConstraint('name', name=op.f('uq_indian_states_name')),
    sa.UniqueConstraint('short_code', name=op.f('uq_indian_states_short_code'))
    )
    op.create_table('news_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('homepage_url', sa.String(length=2048), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('credibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('country_code IS NULL OR length(country_code) = 2', name=op.f('ck_news_sources_country_code_length')),
    sa.CheckConstraint('credibility_score IS NULL OR (credibility_score >= 0 AND credibility_score <= 100)', name=op.f('ck_news_sources_credibility_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_sources')),
    sa.UniqueConstraint('name', 'source_type', name='uq_news_sources_name_type')
    )
    op.create_index('ix_news_sources_country_code', 'news_sources', ['country_code'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('primary_category', sa.String(length=100), server_default=sa.text("'General'"), nullable=False),
    sa.Column('sentiment', sa.String(length=30), server_default=sa.text("'Unknown'"), nullable=False),
    sa.Column('language_code', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('ai_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('share_caption', sa.Text(), nullable=True),
    sa.Column('social_card_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_s3_uri', sa.String(length=2048), nullable=True),
    sa.Column('processed_s3_uri', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_hash IS NULL OR content_hash ~ '^[A-Fa-f0-9]{64}$'", name=op.f('ck_articles_content_hash_format')),
    sa.CheckConstraint('length(language_code) BETWEEN 2 AND 10', name=op.f('ck_articles_language_code_length')),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], name=op.f('fk_articles_source_id_news_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('canonical_url', name=op.f('uq_articles_canonical_url')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_articles_content_hash')),
    sa.UniqueConstraint('url', name=op.f('uq_articles_url'))
    )
    op.create_index('ix_articles_ai_processed', 'articles', ['ai_processed'], unique=False)
    op.create_index('ix_articles_language_code', 'articles', ['language_code'], unique=False)
    op.create_index('ix_articles_primary_category', 'articles', ['primary_category'], unique=False)
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_source_id', 'articles', ['source_id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['indian_states.code'], name=op.f('fk_districts_state_code_indian_states'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('state_code', 'name', name='uq_districts_state_name'),
    sa.UniqueConstraint('state_code', 'slug', name='uq_districts_state_slug')
    )
    op.create_index('ix_districts_state_code', 'districts', ['state_code'], unique=False)
    op.create_table('user_favorite_countries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(country_code) = 2', name=op.f('ck_user_favorite_countries_country_code_length')),
    sa.CheckConstraint('priority BETWEEN 1 AND 2', name=op.f('ck_user_favorite_countries_favorite_country_priority_range')),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_user_favorite_countries_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'country_code', name=op.f('pk_user_favorite_countries')),
    sa.UniqueConstraint('user_id', 'priority', name='uq_user_favorite_countries_user_priority')
    )
    op.create_table('user_favorite_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['indian_states.code'], name=op.f('fk_user_favorite_states_state_code_indian_states'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_user_favorite_states_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'state_code', name=op.f('pk_user_favorite_states'))
    )
    op.create_table('article_countries',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), server_default=sa.text('1.0000'), nullable=False),
    sa.CheckConstraint('length(country_code) = 2', name=op.f('ck_article_countries_country_code_length')),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_article_countries_relevance_score_range')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_countries_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'country_code', name=op.f('pk_article_countries'))
    )
    op.create_table('article_districts',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_article_districts_relevance_score_range')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_districts_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_article_districts_district_id_districts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('article_id', 'district_id', name=op.f('pk_article_districts'))
    )
    op.create_table('article_labels',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_labels_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'label', name=op.f('pk_article_labels'))
    )
    op.create_table('article_states',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_article_states_relevance_score_range')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_states_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_code'], ['indian_states.code'], name=op.f('fk_article_states_state_code_indian_states'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('article_id', 'state_code', name=op.f('pk_article_states'))
    )
    op.create_index('ix_article_states_state_score', 'article_states', ['state_code', 'relevance_score'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_cities_district_id_districts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_code'], ['indian_states.code'], name=op.f('fk_cities_state_code_indian_states'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('state_code', 'name', name='uq_cities_state_name'),
    sa.UniqueConstraint('state_code', 'slug', name='uq_cities_state_slug')
    )
    op.create_index('ix_cities_district_id', 'cities', ['district_id'], unique=False)
    op.create_index('ix_cities_state_code', 'cities', ['state_code'], unique=False)
    op.create_table('state_news_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('ranking_date', sa.Date(), nullable=False),
    sa.Column('ranking_window', sa.String(length=20), server_default=sa.text("'24h'"), nullable=False),
    sa.Column('category_filter', sa.String(length=100), server_default=sa.text("'all'"), nullable=False),
    sa.Column('rank_position', sa.SmallInteger(), nullable=False),
    sa.Column('ranking_score', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank_position BETWEEN 1 AND 10', name=op.f('ck_state_news_rankings_rank_position_top_ten')),
    sa.CheckConstraint('ranking_score >= 0', name=op.f('ck_state_news_rankings_ranking_score_nonnegative')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_state_news_rankings_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_code'], ['indian_states.code'], name=op.f('fk_state_news_rankings_state_code_indian_states'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_news_rankings')),
    sa.UniqueConstraint('state_code', 'ranking_date', 'ranking_window', 'category_filter', 'article_id', name='uq_state_rankings_article'),
    sa.UniqueConstraint('state_code', 'ranking_date', 'ranking_window', 'category_filter', 'rank_position', name='uq_state_rankings_position')
    )
    op.create_index('ix_state_rankings_lookup', 'state_news_rankings', ['state_code', 'ranking_date', 'ranking_window', 'category_filter'], unique=False)
    op.create_table('article_cities',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_article_cities_relevance_score_range')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_cities_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_article_cities_city_id_cities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('article_id', 'city_id', name=op.f('pk_article_cities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_cities')
    op.drop_index('ix_state_rankings_lookup', table_name='state_news_rankings')
    op.drop_table('state_news_rankings')
    op.drop_index('ix_cities_state_code', table_name='cities')
    op.drop_index('ix_cities_district_id', table_name='cities')
    op.drop_table('cities')
    op.drop_index('ix_article_states_state_score', table_name='article_states')
    op.drop_table('article_states')
    op.drop_table('article_labels')
    op.drop_table('article_districts')
    op.drop_table('article_countries')
    op.drop_table('user_favorite_states')
    op.drop_table('user_favorite_countries')
    op.drop_index('ix_districts_state_code', table_name='districts')
    op.drop_table('districts')
    op.drop_index('ix_articles_source_id', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_index('ix_articles_primary_category', table_name='articles')
    op.drop_index('ix_articles_language_code', table_name='articles')
    op.drop_index('ix_articles_ai_processed', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_news_sources_country_code', table_name='news_sources')
    op.drop_table('news_sources')
    op.drop_table('indian_states')
    op.drop_table('app_users')
    # ### end Alembic commands ###
